-- FTS5 keyword index for BM25-based chunk recall.
-- token_text stores retrieval tokens generated by application code, which
-- gives Chinese text useful 2-gram/3-gram matching under SQLite unicode61.
CREATE VIRTUAL TABLE IF NOT EXISTS document_chunks_fts USING fts5(
    token_text,
    content UNINDEXED,
    document_id UNINDEXED,
    chunk_index UNINDEXED,
    user_id UNINDEXED,
    tokenize = 'unicode61'
);
